<?php

$lang = array (

'undefined_action'				=>"非法操作,請返回",
'not_login'						=>"您還沒有登錄或注冊，暫時不能使用此功能!!",
'refresh_limit'					=>"論壇設置:刷新不要快于 $db_refreshtime 秒",
'data_error'					=>"讀取數據錯誤,原因︰您要訪問的鏈接無效,可能鏈接不完整,或數據已被刪除!",
'user_not_exists'				=>"用戶<b>{$errorname}</b>不存在",
'password_confirm'				=>"兩次密碼輸入不一致，請重新輸入",
'password_confirm_fail'			=>"密碼驗證失敗",
'password_change_success'		=>"完成密碼修改",
'mail_success'					=>"我們已經發送您的密碼到您的注冊郵箱,請注意查收!",
'mail_failed'					=>"由于服務器郵件系統配置不正確,郵件發送失敗",
'email_error'					=>"您輸入的用戶名和email地址不符，請重新輸入。",
'illegal_tid'					=>"帖子ID非法",
'illegal_email'					=>"信箱沒有填寫或不符合檢查標準，請確認沒有錯誤",
'illegal_OICQ'					=>"OICQ或ICQ號碼不正確",
'illegal_username'				=>"此用戶名包含不可接受字符或被管理員屏蔽,請選擇其它用戶名",
'illegal_password'				=>"密碼包含不可接受字符,請使用英文和數字",
'illegal_customimg'				=>"非法自定義頭像︰必須以 http 開頭，不可包含此字符'|'，必須在(0-185)*(0-200)的大小範圍里",
'illegal_loadimg'				=>"非法頭像類型",
'sign_limit'					=>"簽名不可超過 $gp_signnum 字節",
'introduce_limit'				=>"自我簡介不要超過 500 字節",
'username_limit'				=>"為了避免論壇用戶名混亂,用戶名中禁止使用大寫字母,請使用小寫字母",
'username_same'					=>"此用戶名已經被注冊,請選擇其它用戶名",
'ban_info1'						=>"你已經被管理員禁言, 禁言開始時間 $s_date ，結束時間 $e_date !",
'ban_info2'						=>"你已經被管理員禁言, 類型為永久禁言!",
'ban_info3'						=>'你已經被管理員強制禁言, 你的其他帳號同時也將被禁言!',
'del_error'						=>"沒有選擇要刪除的選項",
'del_success'					=>"完成刪除操作",
'credit_error'					=>"自定義積分ID錯誤",
'most_online'					=>"狀態:發生錯誤,論壇在線會員數已經達到最大值{$db_onlinelmt},請稍後再來!",
'ip_ban'						=>"您的IP被禁止，不能訪問論壇",
'check_error'					=>'認證碼不正確或已過期',
'keyword_error'					=>'關鍵字必須被包含在主題中',

'hack_error'					=>'未安裝此插件或此插件無前台顯示!',

'bk_credit_change_error'		=>"你要轉換的積分大于實際的積分",
'bk_credit_fillin_error'		=>"積分轉換值填寫不正確！必需為大于零的整數",
'bk_credit_type_error'			=>"銀行不支持這種積分轉換方式",
'bk_virement_error'				=>"自己無法給自己轉帳！",
'bk_no_enough_deposit'			=>"您的存款不夠支付轉帳和手續費，無法實現轉帳！",
'bk_virement_count_error'		=>"轉帳數目填寫不正確！必需填寫大于等于{$bk_virelimit}的整數",
'bk_virement_close'				=>"現在不允許轉帳",
'bk_draw_error'					=>"取款金額大于您的存款金額！",
'bk_draw_fillin_error'			=>"取款數目填寫不正確！必需填寫大于零的整數",
'bk_save_error'					=>"存款金額大于您擁有的金額！",
'bk_save_fillin_error'			=>"存款數據錯誤！必需輸入大于零的整數",
'bk_time_limit'					=>"{$bk_timelimit}秒內不允許重新交易",
'bk_close'						=>"銀行被管理員關閉",

'readvote_noright'				=>"對不起，您沒有權限查看投票會員",

'upload_group_right'			=>"用戶組權限︰你所屬的用戶組沒有上傳附件的權限",
'upload_forum_right'			=>"對不起，本論壇只有特定用戶可以上傳附件，請返回",
'upload_close'					=>"附件上傳功能已關閉",
'upload_size_error'				=>"附件{$atc_attachment_name}超過指定大小{$db_uploadmaxsize}字節",
'upload_type_error'				=>"附件{$atc_attachment_name}的類型不符合準則",
'upload_num_error'				=>"您今天上傳的附件已經達到指定個數($gp_allownum 個)",
'upload_error'					=>"上傳附件失敗，造成的原因可能有:附件目錄不可寫(777)、空間在安全模式下、空間大小已不足。",
'upload_content_error'			=>"附件$atc_attachment_name 內容非法,系統已經將其自動刪除!",

'reply_ifcheck'					=>"該貼未通過管理員驗證，不可回復",
'reply_lockatc'					=>"該貼已被鎖定，不可回復",
'reply_group_right'				=>"用戶組權限︰你所屬的用戶組沒有發表回復的權限!",
'reply_forum_right'				=>"本論壇只有特定用戶組才能回復主題,請到其他版塊回貼,以提高等級!",

'postnew_group_right'			=>"用戶組權限︰你所屬的用戶組沒有發表主題的權限!",
'postnew_forum_right'			=>"本論壇只有特定用戶組才能發表主題,請到其他版塊發貼,以提高等級!",
'postnew_group_vote'			=>"用戶組權限︰你所屬的用戶組沒有發表投票的權限",
'postnew_forum_active'          =>"本版塊只有特定用戶組才能發表活動主題,請到其他版塊發貼,以提高等級!",
'postnew_group_active'			=>"用戶組權限︰你所屬的用戶組沒有發起活動的權限",

'modify_noper'					=>"您無權限編輯別人的貼子",
'modify_locked'					=>"該貼已被鎖定，不可編輯",
'modify_admin'					=>"您無權編輯管理員或總版主的帖子",
'modify_timelimit'				=>"拒絕用戶編輯:您已超過編輯時間限制 $gp_edittime 分鐘",
'vote_not_modify'               =>"該投票主題不允許修改投票結果!",
'modify_group_right'			=>"您所在的用戶組,沒有權限刪除自己的帖子",
'modify_replied'				=>"主題已被回復,不能刪除",


'postfunc_noempty'				=>"不接受空選項",
'postfunc_money_limit'			=>"出售價格錯誤,應在0-1000之間",
'postfunc_subject_limit'		=>"標題為空或標題太長(請控制在{$db_titlemax}字節)",
'postfunc_content_limit'		=>"文章長度錯誤(請控制在{$db_postmin}-{$db_postmax}字節)",
'postfunc_upgrade_error'		=>"無此提升方式",

'msg_refuse'					=>"您發送的消息被用戶拒絕",

'forumpw_pwd_error'				=>"密碼錯誤,請重新輸入密碼",
'forumpw_guest'					=>"游客無權登錄加密版塊",
'forumpw_needpwd'				=>"本版塊為加密版塊,需密碼驗證( 游客無權登錄此版塊)",

'forum_hidden'					=>"本版塊為隱藏版塊,您無權進入",
'forum_jiami'					=>"對不起,本版塊為認證版塊,您沒有權限查看此版塊的內容",
'forum_former'					=>"本版塊為正規版塊,只有注冊會員才能進入",
'forum_guestlimit'				=>"對不起，本版塊只允許注冊會員進入",

'sort_group_right'				=>"用戶組權限︰你所屬的用戶組不能查看統計與排行",

'sendpwd_limit'					=>"<font color=red>發送失敗</font>:請不要在 $gp_postpertime 秒內連續性的使用此功能.",

'sendeamil_subject_limit'		=>"郵件標題為空，請填寫",
'sendeamil_content_limit'		=>"請填寫郵件內容並在20字節之上",
'sendeamil_limit'				=>"<font color=red>發送失敗</font>:不要連續發送郵件.請等候....",
'sendeamil_refused'				=>"用戶{$userdb[username]}不接受郵件",

'search_opensch'				=>"由于網站流量的原因, 站點開放搜索時間為 $db_schstart:00 點到 $db_schend:00 點 !",
'no_condition'					=>"請輸入搜索條件.",
'search_none'					=>"沒有查找匹配的內容",
'search_forum_right'			=>"您無權搜索此版塊帖子",
'search_group_right'			=>"用戶組權限︰你所屬的用戶組不能使用搜索功能",
'search_limit'					=>"對不起{$gp_searchtime}秒內只能進行一次搜索",
'search_word_limit'				=>"關鍵字長度要大于2",
'search_cate'					=>"不能搜索分類",
'illegal_keyword'				=>'關鍵字非法.',
'illegal_author'				=>'用戶名非法.',

'reg_email_fail'				=>"帳號需要激活,激活郵件發送失敗,請聯系管理員!",
'reg_email_success'				=>"您的帳號需要激活,我們已經發送了一封郵件到您的郵箱，請查收!",
'reg_username_limit'			=>"注冊名長度錯誤,請控制在 $rg_regminname - $rg_regmaxname 字節以內",
'reg_repeat'					=>"您已經是注冊成員,請不要重復注冊!",
'reg_limit'						=>"24小時內只能注冊一次",
'reg_close'						=>"對不起,目前論壇禁止新用戶注冊,請返回!",
'reg_jihuo_fail'				=>"激活失敗,錯誤原因:用戶名不存在或驗證參數有誤!",
'reg_jihuo_success'				=>"完成激活密碼,您的帳號已經激活,謝謝您的支持",
'reg_reason'					=>'請填寫注冊原因。',

'read_locked'					=>"此帖被管理員關閉，暫時不能瀏覽",
'read_check'					=>"這篇帖子還沒通過管理員驗證，暫時不能查看",
'read_group_right'				=>"用戶組權限︰你所屬的用戶組沒有瀏覽帖子的權限",

'pro_custom_fail'				=>"要使用自定義頭像功能前提 : 請先刪除上傳的頭像",
'pro_loadimg_fail'				=>"您已經上傳過頭像，要重新上傳頭像請先刪除原來上傳的頭像",
'pro_loadimg_close'				=>"頭像上傳功能已關閉",
'pro_loadimg_right'				=>"用戶組權限︰你所屬的用戶組沒有上傳附件的權限",
'pro_loadimg_limit'				=>"上傳的頭像超過指定大小$db_imgsize 字節",
'pro_loadimg_sizelimit'			=>"上傳的頭像必須在(0-$db_imgwidth)*(0-$db_imglen)的大小範圍里",
'pro_loadimg_error'				=>"上傳的頭像錯誤︰非法操作或頭像無效!",
'pro_manager'					=>"創始人密碼請到後台修改",
'pro_emailcheck'				=>'系統開啟了郵件驗證系統，不允許更改郵件信息。',

'post_wordsfb'					=>"警告︰ 您提交的內容中含有不良言語 '<font color='red'>$banword</font>'！",
'post_gp_limit'					=>"用戶組權限︰你所屬的用戶組每日最多能發 $_G[postlimit] 篇帖子.",
'post_limit'					=>"灌水預防機制已經打開，在{$gp_postpertime}秒內不能發貼",
'post_newrg_limit'				=>"新注冊用戶$db_postallowtime 小時內不能發帖！",
'post_check'					=>"您還沒通過管理員驗證,需要通過管理員驗證才能發言！",
'post_openpost'					=>"由于工作力度與時間原因, 站點開放發帖時間為 $db_poststart:00 點到 $db_postend:00 點 !",
'post_vote_only'				=>"投票版塊只允許發起投票",
'post_recycle'					=>"本版為回收站，不能發帖",
'vote_num_limit'				=>"投票選項個數超過最大限制（最大︰{$db_selcount}個）。",
'notice_illegalid'				=>"無效公告ID",

'msg_ban_fail'					=>"屏蔽列表修改失敗",
'msg_ban_success'				=>"完成屏蔽列表修改",
'msg_limit'						=>"<font color=red>發送失敗</font>:請不要在 $gp_postpertime 秒內連續性的發送短消息.",
'msg_subject_limit'				=>"標題不得大于75字節,內容不得大于1500字節",
'msg_empty'						=>"用戶名，標題或內容為空.",
'msg_group_right'				=>"用戶組權限︰你所屬的用戶組沒有發送短消息權限",
'msg_error'						=>"該信息已被刪除",

'member_right'					=>"用戶組權限︰你所屬的用戶組不能查看會員列表",

'mawhole_count'					=>"一次刪除，復制或移動帖子不能超過500貼",
'mawhole_error'					=>"不能將帖子復制或移動到分類版塊內",
'mawhole_nodata'				=>"沒有要刪除或移動的帖子數據",
'mawhole_right'					=>"您的等級不足,沒有此管理權限",
'mawhole_notype'				=>"該版塊沒有設置主題分類",

'admin_forum_right'				=>"你無權管理其他版塊的帖子",

'masigle_top'					=>"您沒有管理分類置頂或總置頂的權限",
'masigle_point'					=>"不能超過您的評分上限，今天剩余評分點數為{$leavepoint}",
'masigle_creditlimit'			=>"一次評分不能大于{$maxper},或小于{$minper}",
'masigle_credit_error'			=>"積分點數必須為數字",
'masigle_credit_right'			=>"你無權對此積分進行評分",
'masigle_manager'				=>"除創始人外.不能給自己帖子評分",
'masigle_ban_fail'				=>"禁言失敗，{$username}不為會員組，只能禁言會員組",
'member_havebanned'				=>"用戶“{$username}”已經被禁言",
'masigle_ban_right'				=>"你沒有永久封禁會員的權限",
'masigle_ban_limit'				=>"你能封禁用戶的最大天數為{$SYSTEM[banmax]}天",

'login_forbid'					=>"已經連續 6 次密碼輸入錯誤,您將在 10 分鐘內無法正常登錄,還剩余 $L_T 秒",
'login_pwd_error'				=>"密碼錯誤,您還可以嘗試 $L_T 次",
'login_jihuo'					=>"你的帳號沒有激活，請先到您注冊的郵箱里激活帳號!<br /><br />如果您的郵箱無法收到郵件，您可以點擊這里，<a href=\"remail.php?uid=$men_uid\"><font color=\"blue\">進行郵件重發!</font></a>",
'login_empty'					=>"用戶名或密碼為空",
'login_have'					=>"您已經為會員身份,請不要重復登錄!",

'job_vote_num'					=>"投票個數超過指定個數",
'job_vote_sel'					=>"沒有選擇投票項",
'job_havevote'					=>"您已經參與了這次投票,請不要作弊",
'job_vote_lock'					=>"投票失敗,帖子已被鎖定！",
'job_vote_right'				=>"用戶組權限︰你所屬的用戶組沒有投票權限",
'job_havebuy'					=>"您已經購買此貼.請不要重復!",
'sell_error'					=>"出售價格錯誤",
'job_buy_noenough'				=>"您的 {$db_moneyname} 不足，您當前擁有 $money {$db_moneyname}，購買此貼需要 {$sellmoney} {$db_moneyname}",
'job_viewtody_close'			=>"後台核心設置關閉統計.需要管理員打開統計才能使用此功能!",
'job_favor_del'					=>"沒有指定刪除收藏的主題!",
'job_favor_error'				=>"您已經收藏了該主題。",
'job_favor_full'				=>"您的收藏夾已滿，收藏夾最大容量為︰{$_G[maxfavor]}，請整理收藏夾後再收藏該主題。",
'job_attach_right'				=>"您無權限刪除附件",
'job_attach_error'				=>"附件不存在",
'job_attach_rvrc'				=>"您的{$db_rvrcname}小于下載附件所需{$db_rvrcname}，您目前的{$db_rvrcname}︰{$userrvrc}，下載該附件需要威望︰{$needrvrc}",
'job_attach_group'				=>"用戶組權限︰你所屬的用戶組沒有下載附件的權限",
'job_attach_forum'				=>"對不起，本論壇只有特定用戶可以下載附件，請返回",
'job_delimg_error'				=>"刪除失敗，您沒有使用頭像上傳功能或上傳頭像數據錯誤",

'ip_change'						=>"用戶密碼已更改 或 站點開啟了安全認證 , 需要重新登錄!<br><br>如果您無法退出,請點選IE 工具 => 選項 然後手動清除COOKIE",

'no_right'						=>"不能訂閱本版文章",

'have_report'					=>"你已經報告過這篇帖子",
'report_success'				=>"完成帖子報告",
'report_right'					=>"用戶組權限︰你所屬的用戶組不能使用報告功能",

'profile_right'					=>'用戶組權限︰你所屬的用戶組不能查看會員資料',

'no_markright'					=>'用戶組權限︰你所屬的用戶組沒有評分權限.',
'pingtime_over'                 =>"評分超時，你不能對此帖進行評分!",
'no_markagain'					=>'你已經評過分了，你所屬的用戶組沒有重復評分的權限.',
'member_credit_error'			=>'評分點數錯誤，請輸入一個大于或小于零整數.',

'forum_locked'					=>"該版塊設置了鎖定 {$forumset[lock]} 天前的帖子，發帖日期超過 {$forumset[lock]} 天的帖子將被鎖定，不允許回復。",

'forum_creditlimit'				=>"<table cellspacing=1 cellpadding=3 $i_table><tr><td class=head colspan=2><b>該版塊設置了限制積分訪問，以下積分為訪問該版塊需要的最低積分要求</b></td></tr>
									<tr class=f_one><td>積分要求</td><td>您現在的積分</td></tr>
									<tr class=f_one><td>{$db_rvrcname}︰{$forumset[rvrcneed]}</td><td>{$db_rvrcname}︰{$userrvrc}</td></tr>
									<tr class=f_one><td>{$db_moneyname}︰{$forumset[moneyneed]}</td><td>{$db_moneyname}︰{$winddb[money]}</td></tr>
									<tr class=f_one><td>{$db_creditname}︰{$forumset[creditneed]}</td><td>{$db_creditname}︰{$winddb[credit]}</td></tr>
									<tr class=f_one><td>發帖數︰{$forumset[postnumneed]}</td><td>發帖數︰{$winddb[postnum]}</td></tr>
									</table>",

'unenough_money'				=>"您的{$db_currencyname}不足，不能購買相應的道具，{$db_currencyname}獲得途徑 <a href=\"userpay.php?action=change\"><font color=\"blue\">{$db_currencyname}轉換</font></a> <a href=\"userpay.php\"><font color=\"blue\">{$db_currencyname}充值</font></a>",
'unenough_nums'					=>'您要轉讓的道具數量大于您擁有的道具數量。',
'unenough_sellnum'				=>'您要購買的道具數量超過了用戶出售的道具數量。',
'unenough_toolnum'				=>'您的道具數量不足,無法進行轉讓操作.',
'unenough_stock'				=>'您要購買的道具數量超過了改道具的系統庫存數量。',
'no_stock'						=>'系統庫存不足。',
'illegal_nums'					=>'您輸入的數字為非法數字，請輸入一個大于 “0” 的“整數”。',
'numerics_checkfailed'			=>'您提交的數據中包含非法數據,請返回重新操作.',
'empty_credit'					=>'請填寫需要轉換的積分。',
'noenough_currency'				=>"您的{$db_currencyname}不足，{$db_currencyname}獲得途徑 <a href=\"userpay.php?action=change\"><font color=\"blue\">{$db_currencyname}轉換</font></a> <a href=\"userpay.php\"><font color=\"blue\">{$db_currencyname}充值</font></a>",
'change_credit_error'			=>'你要轉換的積分超過你當前擁有的積分。',
'trade_close'					=>'管理員關閉了用戶交易功能。',
'toolcenter_close'				=>'管理員關閉道具中心關閉',

'tool_close'					=>"對不起，該道具未啟用，您不能使用該道具。",
'tool_grouplimit'				=>"您所屬的用戶組不能使用該道具，<a href=\"hack.php?H_name=toolcenter&action=buy&id=$toolid\"><b>點擊查看道具詳細資料</b></a>。",
'tool_creditlimit'				=>"您的積分沒有達到道具的使用積分要求，<a href=\"hack.php?H_name=toolcenter&action=buy&id=$toolid\"><b>點擊查看道具詳細資料</b></a>。",
'tool_forumlimit'				=>"該版塊不能使用道具，<a href=\"hack.php?H_name=toolcenter&action=buy&id=$toolid\"><b>點擊查看道具詳細資料</b></a>。",
'nothistool'					=>"您的道具箱中沒有該道具，您需要到 <a href=\"hack.php?H_name=toolcenter\"><b><i>道具中心</i></b></a> 購買該道具後才能使用",
'tool_authorlimit'				=>"對不起，該道具只對自己發表的帖子有效。",
'tool_error'					=>'使用道具時，傳遞的參數錯誤，請返回重試。',

'toolmsg_1_success'				=>"道具使用成功，已經將您的‘{$db_rvrcname}’負分轉為 0。",
'toolmsg_1_failed'				=>"道具使用失敗，您的‘{$db_rvrcname}’不是負分，不需要轉換，您可以在以後有需要時使用此道具。",
'toolmsg_2_success'				=>'道具使用成功，已經將您的所有積分負分都已經轉為 0。',
'toolmsg_2_failed'				=>'道具使用失敗，您的積分中沒有負分，不需要轉換，您可以在以後有需要時使用此道具。',
'toolmsg_4_failed'				=>'道具使用失敗，您的帖子已經在版塊中置頂，不需要對這個帖子使用該道具。',
'toolmsg_5_failed'				=>'道具使用失敗，您的帖子已經在分類中置頂，不需要對這個帖子使用該道具。',
'toolmsg_6_failed'				=>'道具使用失敗，您的帖子已經在整個論壇置頂，不需要對這個帖子使用該道具。',
'toolmsg_8_success'				=>"道具使用成功，您的用戶名已經改為 {$pwuser} 。",

'groupright_show'				=>'用戶組權限，你所屬的用戶組沒有使用展區功能。',

'showsign_error'				=>'後台沒有開啟此功能。',
'showsign_success'				=>'簽名展示設置成功。',

'no_tool'						=>"您沒有可以使用的道具，請先到 <a href='hack.php?H_name=toolcenter'><font color='blue'>系統交易中心</font></a> 購買道具。",

'username_exists'              => '該用戶名已經被注冊，請選用其他用戶名。',
'username_not_exists'          => '恭喜您，該用戶名還未被注冊，您可以使用這個用戶名注冊！',

'colony_close' => "管理員關閉了{$cy_name}功能。",
'colony_reglimit' => "系統不允許注冊新的{$cn_name}。",
'colony_groupright' => "用戶組權限，你所在的用戶組沒有創建{$cn_name}的權限。",
'colony_creatfailed' => "您的{$db_currencyname}不足，創建一個{$cn_name}需要支付 {$cn_createmoney} 個{$db_currencyname}，{$db_currencyname}獲得途徑 <a href=\"userpay.php?action=change\"><font color=\"blue\">{$db_currencyname}轉換</font></a> <a href=\"userpay.php\"><font color=\"blue\">{$db_currencyname}充值</font></a>",
'colony_numlimit' => "您允許創建的{$cn_name}個數已滿，每個用戶最多只能建{$cn_allowcreate}個{$cn_name}。",
'colony_class' => "請選擇{$cn_name}的所屬分類。",
'colony_emptyname' => "{$cn_name}的名稱不能為空。",
'colony_samename' => "您輸入的{$cn_name}名稱已經存在，請選擇另一個名稱。",
'colony_joinlimit' => "加入{$cn_name}失敗，您允許加入的{$cn_name}個數已滿。",
'colony_memberlimit' => "加入{$cn_name}失敗，該{$cn_name}人數已滿。",
'colony_joinrefuse' => "該{$cn_name}拒絕新成員加入。",
'colony_joinfail' => "您的{$db_currencyname}不足，加入該{$cn_name}需要支付 {$cydb[intomoney]} 個{$db_currencyname}，{$db_currencyname}獲得途徑 <a href=\"userpay.php?action=change\"><font color=\"blue\">{$db_currencyname}轉換</font></a> <a href=\"userpay.php\"><font color=\"blue\">{$db_currencyname}充值</font></a>",
'colony_passfail' => "用戶 <b>{$rt[username]}</b> {$db_currencyname}不足，不能通過審核。",
'colony_nocheck' => "您還沒通過管理員審核，暫時不能使用{$cn_name}功能。",
'colony_alreadyjoin' => "加入{$cn_name}失敗，你已加入了該{$cn_name}。",
'colony_realname' => '真實姓名不能為空，請輸入您的真實姓名。',
'colony_samerealname' => '對不起，您輸入的真實姓名已經存在，請重新輸入。',
'colony_cardright' => "您還不是這個{$cn_name}的會員，不能查看名片夾！",
'colony_editcard' => "您還不是這個{$cn_name}的會員，不能使用名片功能！",
'colony_nocard' => "你要編輯的名片不存在。",
'colony_noseecard' => '您要查看的名片不存在。',
'colony_boardright' => "你不是該{$cn_name}的成員，無權訪問該{$cn_name}的討論區。",
'colony_posterror' => '標題或內容為空。',
'colony_editright' => '你沒有權限編輯他人的帖子',
'colony_delright' => "你沒有權限刪除他人的帖子。",
'colony_donateright' => "你不是該{$cn_name}的成員，不能使用捐獻功能。",
'colony_donateerror' => "捐獻的{$db_currencyname}數必須是大于零的整數。",
'colony_donatefail' => "捐獻失敗，您捐獻的{$db_currencyname}數大于您擁有的{$db_currencyname}數，{$db_currencyname}獲得途徑 <a href=\"userpay.php?action=change\"><font color=\"blue\">{$db_currencyname}轉換</font></a> <a href=\"userpay.php\"><font color=\"blue\">{$db_currencyname}充值</font></a>",
'colony_donatesuccess' => "捐獻成功。",
'colony_quitfail' => "您是該{$cn_name}的創建者，可以使用“解散{$cn_name}”來解散這個{$cn_name}。",
'colony_adminright' => "您不是{$cn_name}管理員，不能使用此功能.",
'colony_sizelimit' => "您上傳的圖片太大超過了系統限制的大小。",
'colony_uploadfail' => "圖片上傳失敗",
'colony_lenthlimit' => "上傳的標志必須在（0 - $cn_imgheight ）*（0 - $cn_imgwidth ）的大小範圍里",
'colony_joinmoney' => "會員加入{$cn_name}至少需要{$db_currencyname}個數︰{$cn_joinmoney}",
'colony_addamin' => '管理員設置完成。',
'colony_delladminfail' => "不能取消{$cn_name}創建者的管理員身份。",
'colony_deladmin' => '取消管理員完成。',
'colony_pass' => '審核會員完成。',
'colony_delfail' => "不能刪除{$cn_name}創建者。",
'colony_del' => '刪除會員完成。',
'colony_cancelclose' => "系統關閉了解散{$cn_name}的功能。",
'colony_cancel' => "您不是{$cn_name}的創建者，無權解散該{$cn_name}.",

'sale_error' => '交易帳號，商品名稱，商品價格為空或格式錯誤！',
'seller_error' => '交易帳號格式錯誤',

'olpay_seterror'=>'網上支付設置錯誤，請管理員登錄後台“網上支付設置”檢查設置是否正確！',
'olpay_numerror'=>"對不起，您輸入的金額無效，請輸入一個大于{$db_rmblest}的整數。（網絡支付最低人民幣︰{$db_rmblest} 元 ）",
'olpay_paypalerror'=>'貝寶信息設置錯誤，請管理員登錄後台“網上支付設置”檢查設置是否正確！',
'olpay_alipayerror'=>'交易信息設置錯誤，請管理員登錄後台“網上支付設置”檢查設置是否正確！',
'olpay_pay99error'=>'快錢信息設置錯誤，請管理員登錄後台“網上支付設置”檢查設置是否正確！',

'medal_close'=>'系統沒有開啟勛章功能',
'medal_noreason'=>'請輸入操作理由！',
'medal_groupright'=>'您所屬的用戶組沒有頒發（收回）勛章的權限',
'medal_alreadyhave'=>'該用戶已經已經擁有此勛章',
'medal_none'=>'該用戶沒有此勛章',
'medal_dellog'=>'只有管理員才能刪除勛章頒發日志',
'medal_nomedal'=>'請選擇要授予的勛章！',

'blog_close'=>'系統沒有開啟博客功能',
'username_empty' => '用戶名為空，請填寫用戶名！',

'colony_cnamelimit'	=> "{$cn_name}名稱太長，請控制在 20字節 以內",
'colony_descriplimit'	=> "{$cn_name}簡介太長，請控制在 255字節 以內",
'colony_annoucelimit'	=> "{$cn_name}公告太長，請控制在 255字節 以內",

'virement_success'	=> "{$db_currencyname}轉帳成功。",
'empty_password'	=> '請輸入驗證密碼',
'password_error'	=> '密碼驗證失敗，請輸入正確的密碼',
'virement_closed'	=> "系統沒有開啟{$db_currencyname}轉帳功能",
'currency_limit'	=> "系統設定最低轉帳金額為︰{$cy_virelimit} {$db_currencyname}",

'realname_limit' => '真實姓名長度錯誤，請控制在 20字節以內',
'tel_limit' => '電話長度錯誤，請控制在 15字節以內',
'intro_limit' => '個人簡介太長，請控制在 255字節 以內',
'colony_manager'	=> "只有{$cn_name}的創建者有添加和刪除管理員的權限",
'colony_currency'	=> "系統沒有開啟{$cn_name}{$db_currencyname}管理功能",
'colony_noenough_currency'	=> "{$cn_name}的{$db_currencyname}不足，您可以使用捐獻功能增加{$cn_name}的{$db_currencyname}",
'no_colony_member'	=> "$pwuser 不是該{$cn_name}的會員，此功能只允許給朋友圈中的會員增加{$db_currencyname}",
'colony_currency_right'=>"只有{$cn_name}創建者有權限管理{$cn_name}的{$db_currencyname}。",

'sendmail_closed'=>"系統沒有開啟郵件發送功能。",
'no_atclog_right'=>'用戶組權限︰你所屬的用戶組不允許使用“查看帖子操作記錄”的權限。',
'no_viewright_right'=>'用戶組權限︰你所屬的用戶組不允許使用“用戶組權限查看”的權限。',
'enterreason'	=> "請輸入操作理由。",

'illegal_icon' => "引用頭像鏈接不能超過85個字節",
'friend_already_exists'=>"該用戶已經在您的好友列表中。",
'field_lenlimit'=>"您輸入的“<b>{$val[title]}</b>”太長，請控制在{$val[maxlen]}字節以內",
'field_empty'=>"“<b>{$val[title]}</b>”為必填內容，請返回填寫！",

'special_allowbuy'=>"該用戶組身份不允許用戶使用“{$db_currencyname}”購買。",
'special_selllimit'=>'您要購買用戶組身份的天數小于該用戶組“最短購買天數”限制！',
'specialgroup_exists'=>"您已經購買了該用戶組身份，用戶組身份到期時間︰{$enddate}。",
'specialgroup_error'=>'您要購買的用戶組不存在。',
'specialgroup_noneed'=>'您已經是該用戶組成員，不需要購買！',

'gross_error' => "訂單信息錯誤，請聯系管理員解決！",
'passport_close' => "系統沒有開啟通行證功能。",
'days_limit' => "您的邀請碼已過期!",
'invcode_error' => "您要發送的邀請碼不存在!",
'group_invite' => "您所在的組別沒有購買邀請碼的權限!",
'invite_costs' => "您的積分不足以購買邀請碼!",
'inv_limitdays'=> "邀請碼購買時間限制，請稍侯",

'reward_noright' => "您沒有權限管理其他人的懸賞貼!",
'reward_time_limit'=>"懸賞時間沒有超過規定時間，不能強制結案!",
'rewardmsg_success'=>"你已經成功地給斑主發送短消息，很快能得到答復!",
'reward_no_forumadmin'=>"對不起，該斑塊沒有斑主，您的申請無法提交!",
'reward_have_sendmsg'=>"您已經給版主發過消息了，請勿重復發短消息!",
'reward_have'=>"熱心助人獎只允許加一次,您已經為該會員加過熱心助人獎了!",
'invcode_empty'=>"本站開啟了邀請注冊功能，沒有邀請碼將無法正常注冊!",
'illegal_invcode'=>"邀請碼錯誤!",
'read_shield'=>"錯誤操作,該帖已被屏蔽!",
'read_unshield'=>"錯誤操作,該帖沒有被屏蔽!",
'masingle_data_error'=>'鏈接地址條件不足!',
'remind_data_empty'=>'提示內容不能為空!',
'remind_length'=>'提示內容過長，請刪掉一些!',
'medallog_del_error'=>"該勛章未到期，不能刪除日志!",
'medal_reason'=>"過期",
'credit_limit'=>"您設置的積分值不能小于系統規定的最小值!",
'reward_credit_limit'=>"您的積分不足，無法進行此操作!",
'reward_credit_error'=>'您的積分類型不合法!',
'reward_change_error'=>"該貼沒有設置熱心助人積分",
'force_tid_select'=>'本版塊開啟強制主題分類功能,請選擇文章分類!',
'unite_data_error'=>'您輸入的數據為空或不是數字!',
'unite_limit'=>'特殊帖無法被合並!',
'unite_fid_error'=>"不同版塊的帖子無法被合並!",
'upload_money_limit'=>"您的金錢不足 {$gp_uploadmoney} ,無法上傳附件!",
'time_out'=>'已經超過截止日期，無法申請!',
'num_full'=>'您申請的活動已經達到最大人數，無法再申請了!',
'apply_gender_error'=>'您的性別不符合要求，無法申請!',
'have_act'=>'您已經申請過該次活動了!',
'actid_view_error'=>'您沒有參加該次活動或者尚未被批準!',
'selid_illegal'=>'請選擇操作對象!',
'active_manager_right'=>'您不是活動發起人，沒有管理權限!',
'contact_empty'=>'聯系方式不能為空!',
'active_data_empty'=>'必填數據不能為空，請認真填寫!',
'deadline_limit'=>'截止日期不得小于當前時間!',
'starttime_limit'=>'開始時間不得小于截止日期!',
'endtime_limit'=>'結束時間不得小于開始時間',
'rightwhere'=>'您沒有該版塊的管理權限!',
'email_check'=>'為避免無法收到論壇信件，請使用指定郵箱進行注冊!',
'remail_error'=>'您還不是本站會員，或者已經通過驗證!',
'remail_rgemail_error'=>'您填寫的郵箱與注冊的郵箱不符，請重新填寫!',
'remail_success'=>'郵件重發成功，請查收!',
'not_forumadmin'=>'您不是版主或者不是該版塊的版主!',
'inv_close'=>'站點沒有開啟邀請注冊功能!',
'delping_credit_error'=>'評分積分類型錯誤!',
'have_not_showping'=>'錯誤操作,你沒有給該帖評分!',
'favor_sel_error'=>'請選擇操作對象!',
'tid_favor_error'=>'該帖已收藏!',
'favor_cate_error'=>'分類名稱為空，或者長度超過20個字符!',
'favor_cate_limit'=>'分類名稱不能含有 “,” 字符!',
'type_error'=>'你要刪除的分類不存在!',
'illegal_request'=>'非法請求，請返回重試!',
'ftp_not_exists'=>'您的 php 不支持 ftp ,請到後台關閉 ftp 功能!',
'content_same'=>'請勿連續發表相同內容的主題!',
'tofriend_msgerror'=>'標題和內容不能為空,請填寫!',
'illegal_imgtype'=>'非法圖片類型',
);
?>