<?php
$lang=array(

'operate_success'		=> "操作完成",
'have_login'			=> "您已經順利登錄",
'login_out'				=> "狀態︰您已經順利退出網站",
'enter_thread'			=> "<a href=thread.php?fid=$fid>[ 發貼完畢點擊進入主題列表 ]</a>",
'reg_success'			=> "恭喜您,完成注冊現在可以開始使用您的會員權利了",
'mail_success'			=> "郵件發送完成",
'enter_c_thread'		=> "<a href=c_thread.php?fid=$fid>[ 發貼完畢點擊進入主題列表 ]</a>",
'post_check'			=> "文章發表成功,本版塊開啟了發帖審核功能,請等待管理員審核!",
'masigle_ban_success'	=> "完成禁言,將自動跳轉至會員資料頁面",
'update_cache'			=> "正在更新會員排行緩存,請耐心等待!",
'colony_regsuccess'		=> "{$cn_name}注冊成功，進入{$cn_name}基本資料設置",
'colony_joinsuccess'	=> "加入{$cn_name}成功,進入{$cn_name}首頁。",
'colony_cardsuccess'	=> "{$cn_name}名片修改成功。",
'colony_postsuccess'	=> "發言成功。",
'colony_editsuccess'	=> "編輯成功。",
'colony_delsuccess'		=> "刪除成功。",
'colony_quitsuccess'	=> "退出成功。",
'colony_setsuccess'		=> "{$cn_name}基本設置修改成功。",
'colony_cancelsuccess'	=> "{$cn_name}解散成功。",
'showsign_success'		=> "簽名展示設置成功。",
'bank_savesuccess'		=> "完成存款!",
'bank_drawsuccess'		=> "完成取款!",
'bank_viresuccess'		=> "完成轉帳!",
'bank_creditsuccess'	=> "完成積分轉換!",
'blog_enterhomepage'	=> "進入 {$username} 的個人主頁",
'friend_update_success'	=> "好友列表更新成功。",
'complete_list'			=> "該訂單已完成支付。",
'bakup_step'			=>"正在備份數據庫表 $t_name: 共 $rows 條記錄，已經備份至 $c_n  條記錄<br><br>已生成 $f_num 個備份文件，程序將自動備份余下部分",
'bakup_out'				=>"已全部備份,備份文件保存在data目錄下，備份文件為<br>$bakfile",
'backup_data'           =>'論壇進入自動數據備份中，您將無法訪問本論壇',
'group_buy_success'     =>'特殊組購買成功!!',
);
?>