<?php

$lang = array (
	'sell'				=>	"轉讓",
	'sell_descrip'		=>	"[b]{$log[username]}[/b] 轉讓裝備︰ [b]{$log[toolname]}[/b] ,數量︰{$log[nums]}。",
	'buy'				=>	"購買",
	'buy_descrip'		=>	"[b]{$log[username]}[/b] 向系統購買裝備︰ [b]{$log[toolname]}[/b] ,數量︰{$log[nums]},花費︰{$log[money]}。",
	'buyuser_descrip'	=>	"[b]{$log[username]}[/b] 向[b]{$log[from]}[/b]購買裝備︰ [b]{$log[toolname]}[/b] ,數量︰{$log[nums]},花費︰{$log[money]}。",
	'buyself_descrip'	=>	"[b]{$log[username]}[/b] 購回自己轉讓的裝備︰ [b]{$log[toolname]}[/b] ,數量︰{$log[nums]}",
	'change'			=>	"轉換",
	'change_descrip_1'	=>	"[b]{$log[username]}[/b] 使用[b]交易幣轉換[/b]功能，獲得 {$log[creditinfo]}，總計花費交易幣數︰{$log[currency]}",
	'change_descrip_2'	=>	"[b]{$log[username]}[/b] 使用[b]交易幣轉換[/b]功能，轉換 $log[creditinfo] 為交易幣，總共獲得交易幣︰$log[currency]",
	'use'				=>	"使用",
	'tool_1_descrip'	=>	"[b]{$log[username]}[/b] 使用裝備 [b]{$log[toolname]}[/b] ,將負威望轉為 0。",
	'tool_2_descrip'	=>	"[b]{$log[username]}[/b] 使用裝備 [b]{$log[toolname]}[/b] ,將所有負積分轉為 0。",
	'tool_3_descrip'	=>	"[b]{$log[username]}[/b] 使用裝備 [b]{$log[toolname]}[/b] ,將帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 加亮顯示。",
	'tool_4_descrip'	=>	"[b]{$log[username]}[/b] 使用裝備 [b]{$log[toolname]}[/b] ,將帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 在版塊中置頂。",
	'tool_5_descrip'	=>	"[b]{$log[username]}[/b] 使用裝備 [b]{$log[toolname]}[/b] ,將帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 在所在分類中置頂。",
	'tool_6_descrip'	=>	"[b]{$log[username]}[/b] 使用裝備 [b]{$log[toolname]}[/b] ,將帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 在整個論壇中置頂。",
	'tool_7_descrip'	=>	"[b]{$log[username]}[/b] 使用裝備 [b]{$log[toolname]}[/b] ,將帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 提前到該版塊首頁。",
	'tool_8_descrip'	=>	"[b]{$log[username]}[/b] 使用裝備 [b]{$log[toolname]}[/b] ,將自己在論壇的用戶名改為[b]{$log[newname]}[/b]。",
	'tool_9_descrip'	=>	"[b]{$log[username]}[/b] 使用裝備 [b]{$log[toolname]}[/b] ,將帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 加為精華I。",
	'tool_10_descrip'	=>	"[b]{$log[username]}[/b] 使用裝備 [b]{$log[toolname]}[/b] ,將帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 加為精華II。",
	'tool_11_descrip'	=>	"[b]{$log[username]}[/b] 使用裝備 [b]{$log[toolname]}[/b] ,將帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 鎖定。",
	'tool_12_descrip'	=>	"[b]{$log[username]}[/b] 使用裝備 [b]{$log[toolname]}[/b] ,將帖子 [url=$db_bbsurl/read.php?tid=$log[tid]][b]$log[subject][/b][/url] 解除鎖定。",
	'olpay'				=>	"充值",
	'olpay_descrip'		=>	"[b]{$log[username]}[/b] 使用交易幣充值功能，充值金額︰{$log[number]}，獲得交易幣︰{$log[currency]}",
	'colony'			=>	"建群",
	'colony_descrip'	=>	"[b]{$log[username]}[/b] 使用創建群功能創建群[b]{$log[cname]}[/b]，總共花費交易幣︰{$log[currency]}。",
	'join'				=>	"加群",
	'join_descrip'		=>	"[b]{$log[username]}[/b] 加入群[b]{$log[cname]}[/b]，花費交易幣︰{$log[currency]}。",
	'sign'				=>	'簽名',
	'sign_descrip'		=>	"[b]{$log[username]}[/b] 使用簽名展示功能，花費交易幣︰{$log[currency]}。",
	'vire'				=>	'轉帳',
	'vire_descrip'		=>	"[b]{$log[username]}[/b] 使用交易幣轉帳功能，給用戶[b]{$log[toname]}[/b]轉帳 {$log[currency]}交易幣，系統收取手續費︰{$log[tax]}。",
	'donate'			=> '捐獻',
	'donate_descrip'	=> "[b]{$log[username]}[/b] 使用捐獻給所在群($log[cname])捐獻交易幣︰{$log[currency]}。",
	'cyvire_descrip'	=> "[b]{$log[username]}[/b] 使用群交易幣管理功能，給用戶[b]{$log[toname]}[/b]轉帳 {$log[currency]}交易幣，系統收取手續費︰{$log[tax]}。",
	'group'				=> "用戶組",
	'group_descrip'		=> "[b]{$log[username]}[/b] 使用用戶組身份購買功能，購買用戶組($log[gptitle])身份{$log[days]}天，總共花費交易幣數︰{$log[currency]}。",
);
?>