<?php

$lang = array (
'currency'=>'論壇交易幣',
'buy_currency'=>'購買論壇交易幣',
'unpay_list'=>'未支付訂單',
'invite'=>'邀請注冊',
'invite_content'=>"您好:\r\n\t這里是 $db_bbsname 論壇，歡迎使用邀請注冊插件，點擊以下連接，您就可以順利完成注冊！\r\n鏈接地址:$db_bbsurl/register.php?invcode=$invcode[invcode]。\r\n\r\n$db_bbsname 歡迎你!",
'men'=>'先生',
'women'=>'小姐',
'send_content'=>":\n 今天是你 age 生日,祝你生日快樂!",
'send_title'=>'祝你生日快樂',
'cancle'=>'本次懸賞被取消',
'finished'=>'本次懸賞被強行結案',
'js_close'=>'該網站沒有開啟首頁調用功能，需要到論壇核心設置中開啟。',
'js_bindurl'=>'非法調用，系統限制了允許調用論壇內容的域名。',
'js_totalmember'=>'會員總數',
'js_newmember'=>'最新注冊會員',
'js_topic'=>'主題數',
'js_article'=>'帖子數',
'js_today'=>'今 日',
'js_yesterday'=>'昨 日',
'js_highday'=>'最高日',
'js_online'=>'在線總數',
'js_onlinemen'=>'會員數',
'js_onlineguest'=>'游客數',
'js_highonline'=>'最高在線',
'js_happen'=>'發生在',
'js_replies'=>'回復',
'js_hits'=>'點擊',
'mawhole_copy'=>"該帖由 $windid 從 {$forum[$fid][name]} 復制到本區.\t$windid",
);
?>